CREATE TABLE CM_CASHCUSTOMER(
  CC_NAME 				VARCHAR2(20 CHAR),
  CC_GENDER				VARCHAR2(1),
  CC_PHONENUM 			VARCHAR2(11),
  CC_AMOUNT				NUMBER(7,2),
  CC_CONSUMEDT			VARCHAR2(14),
  CC_REMARK				VARCHAR2(100 CHAR),
  CC_TELLER				VARCHAR2(20 CHAR)
);
COMMENT ON TABLE CM_CASHCUSTOMER 					IS '散客消费记录表';
COMMENT ON COLUMN CM_CASHCUSTOMER.CC_NAME 			IS '姓名';
COMMENT ON COLUMN CM_CASHCUSTOMER.CC_GENDER  			IS '柜员性别: F:女 M:男';
COMMENT ON COLUMN CM_CASHCUSTOMER.CC_PHONENUM 		IS '电话号码';
COMMENT ON COLUMN CM_CASHCUSTOMER.CC_AMOUNT 		IS '消费金额';
COMMENT ON COLUMN CM_CASHCUSTOMER.CC_CONSUMEDT 	IS '消费日期';
COMMENT ON COLUMN CM_CASHCUSTOMER.CC_REMARK 		IS '备注';
COMMENT ON COLUMN CM_CASHCUSTOMER.CC_TELLER 		IS '操作柜员';