CREATE TABLE CM_CARDINFO(
  CC_CARDID 			NUMBER(5),
  CC_CUSTOMERID 		VARCHAR(6),
  CC_CARDTYPE 			VARCHAR(1),
  CC_APPLYACCOUNTDT 	VARCHAR(8),
  CC_TOACCOUNTDT 		VARCHAR(8),
  CC_CONSUMTIMES 		VARCHAR(4),
  primary key (CC_CARDID)
);
COMMENT ON TABLE CM_CARDINFO IS '卡信息表';
COMMENT ON COLUMN CM_CARDINFO.CC_CUSTOMERID IS '持卡用户ID';
COMMENT ON COLUMN CM_CARDINFO.CC_CARDTYPE IS '卡类型 1,次卡  2，月卡  3，年卡';
COMMENT ON COLUMN CM_CARDINFO.CC_APPLYACCOUNTDT IS '卡申请日期';
COMMENT ON COLUMN CM_CARDINFO.CC_TOACCOUNTDT IS '  ';
COMMENT ON COLUMN CM_CARDINFO.CC_CONSUMTIMES IS '消费总次数';
