CREATE TABLE CM_DEPOSIT (
  CD_CUSTOMERID 			VARCHAR2(100),
  CD_DEPOSITDT				CHAR(14),
  CD_DEPOSITAMT 			NUMBER(7,2),
  CD_CARDTYPE 				VARCHAR2(1),
  CD_ADDTIMES				VARCHAR2(4),
  CD_DISCOUNTTIMES			VARCHAR2(4),
  CD_DISCOUNTTIME			VARCHAR2(4),
  CD_TELLER 				VARCHAR2(20 CHAR),
  CD_STARTDT				CHAR(14),
  CD_ENDDT					CHAR(14),
  CD_REMARK 				VARCHAR2(50 CHAR),
  CD_RECORDDT				CHAR(14),
  CC_TOTALCOUNT			  	VARCHAR2(10),
  CC_LASTDATE			  	CHAR(14)
);
COMMENT ON TABLE CM_DEPOSIT 						 IS '储值明细表';
COMMENT ON COLUMN CM_DEPOSIT.CD_DEPOSITDT 			 IS '储值日期';
COMMENT ON COLUMN CM_DEPOSIT.CD_DEPOSITAMT 		 IS '储值金额';
COMMENT ON COLUMN CM_DEPOSIT.CD_CARDTYPE   		 IS '卡类型';
COMMENT ON COLUMN CM_DEPOSIT.CD_ADDTIMES   		 IS '新增次数';
COMMENT ON COLUMN CM_DEPOSIT.CD_DISCOUNTTIMES  	 IS '优惠次数';
COMMENT ON COLUMN CM_DEPOSIT.CD_DISCOUNTTIME   	 IS '（年/月卡）优惠时间';
COMMENT ON COLUMN CM_DEPOSIT.CD_TELLE  			 IS '操作柜员';
COMMENT ON COLUMN CM_DEPOSIT.CD_STARTDT   			 IS '年/月卡开始计费日期';
COMMENT ON COLUMN CM_DEPOSIT.CD_ENDDT     			 IS '年/月卡截止计费日期';
COMMENT ON COLUMN CM_DEPOSIT.CD_RECORDDT     		 IS '记帐日期';
COMMENT ON COLUMN CM_DEPOSIT.CC_TOTALCOUNT    		 IS '储值总次数：（次卡）实际次数+优惠次数';
COMMENT ON COLUMN CM_DEPOSIT.CC_LASTDATE     		 IS '储值总时间：(年卡/月卡)实际时间+优惠时间';