CREATE TABLE CM_USER(
  USERID 			VARCHAR2(100) NOT NULL,
  USER_NAME 		VARCHAR2(20 CHAR),
  PASSWORD 			VARCHAR2(20),
  GENDER			VARCHAR2(1),
  USER_LEVEL 		CHAR(1),
  USER_PHONENUM 	VARCHAR2(11),
  USER_STATE		CHAR(1),
  primary key (USERID)
);
COMMENT ON TABLE CM_USER 					IS '员工信息表';
COMMENT ON COLUMN CM_USER.USER_LEVEL 		IS '柜员级别: 0:管理员 1:柜员';
COMMENT ON COLUMN CM_USER.GENDER  			IS '柜员性别: F:女 M:男';
COMMENT ON COLUMN CM_USER.USER_STATE 		IS '柜员状态：0:在职 1:离职';